version: '3.8'

services:
  boletim-sofia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boletim-sofia
    ports:
      - "1307:80"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
